@echo off
echo Starting Treatment Model Python Application...
cd Treatment_Model_Random_Forest
echo Creating virtual environment...
python -m venv venv
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo Installing Python dependencies...
pip install -r requirements.txt
echo Starting Streamlit application...
streamlit run app.py
pause 