@echo off
echo Starting BMI Laravel Application...
cd BMI
echo Installing PHP dependencies...
composer install
echo Installing Node.js dependencies...
npm install
echo Starting Laravel development server...
php artisan serve
pause 