@echo off
echo Starting both BMI and Treatment Model applications...

echo Starting BMI Laravel Application in new window...
start "BMI Laravel App" cmd /k "cd BMI && composer install && npm install && php artisan serve"

echo Starting Treatment Model Python Application in new window...
start "Treatment Model Python App" cmd /k "cd Treatment_Model_Random_Forest && python -m venv venv && call venv\Scripts\activate.bat && pip install -r requirements.txt && streamlit run app.py"

echo Both applications are starting...
echo BMI will be available at: http://localhost:8000
echo Treatment Model will be available at: http://localhost:8501
pause 